#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 389801252                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : dk                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.instagram.android
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/ourwalk_logo_1024px.png            # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Our Walk                                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Our Walk is a participatory tool for mobilizing and engaging people. 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Backscatter
your_link                                 : https://backscatter.dk                     
your_city                                 : Copenhagen                                
email_address                             : info@backscatter.dk
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : backscatterdk
linkedin_username                         : backscatterdk
youtube_username                          :





# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Digital participation
    description                           : Our Walk is an application by Backscatter, a human data science studio based in Copenhagen. Backscatter uses the app to invite people to take photos that express how they feel about the places that surround them. Users are encouraged to react to other people’s photos, allowing us to map how people perceive their surroundings differently.
    fontawesome_icon_name                 : mobile
    
  - title                                 : Try it out
    description                           : To utilise the app for data collection in your area, you need to be assigned to a project by Backscatter. If you want to get involved, reach out to us using the buttons below.
    fontawesome_icon_name                 : star

  - title                                 : Legacy
    description                           : The app builds on the Urban Belonging app, developed as part of Anders Koed Madsen’s Doing Data Together project. It was redeveloped by Backscatter in cooperation with DIGIT srl. The original app was developed by Iain Kettles, designed by Marcos Cisneros, and was in turn inspired by the Snappthis app by Marije ten Brink. The original app is open-source at [urbanbelonging.com](https://urbanbelonging.com/).
    fontawesome_icon_name                 : info-circle


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/DSC_0433.jpg                       # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.5

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
